{"uuid": "2c86fd0b-96ae-4fb5-86a0-0c49db2fb15d", "children": ["15e64eee-2347-4ef9-a563-93f63864d9e0", "3493eccd-35c3-4f02-92ea-d3a5cd44e446", "95e24c81-6f5c-467d-95a5-694ef051a06d", "d1ce0ed8-c313-4ba8-a136-43bf49d7d5af", "98f67c64-6a20-4e18-bbca-ea0ca53c18ed", "fc23736b-86b1-472d-b98a-1d6c0e369e00", "176676eb-4a37-4e09-beaa-7d5458058041", "83ac71f3-bb9a-43a0-a186-bcb395ec34aa", "37af7453-1c31-4148-8d46-ecafa25e98e5", "e3770733-0771-4a59-b014-b880d2d3faa6", "2bd96073-a9d2-4a31-92d0-cb86b95faf36", "66c3bfd6-7b2a-4adc-b0ba-fa95a2161a2c", "a877f9d9-f6c5-4f7b-9a93-081658bc894d", "649f5018-01a6-4eee-afed-6654920c5971"], "befores": [{"name": "driver_class", "status": "broken", "statusDetails": {"message": "_pytest.config.exceptions.UsageError: --driver must be specified\n", "trace": "  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Mish\\Yandex.Practicum\\Sprint_6\\.venv\\lib\\site-packages\\pytest_selenium\\pytest_selenium.py\", line 156, in driver_class\n    raise pytest.UsageError(\"--driver must be specified\")\n"}, "start": 1732921902808, "stop": 1732921902808}], "start": 1732921902808, "stop": 1732921904105}